# -*- coding: utf-8 -*-
"""SQL DATABASE IMPORT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqGY3xgBjrsAfXtT2DnXvmp-X2x71zGW
"""

import pandas as pd

df = pd.read_csv('US Crime Data exploration analysis/Crime_us.csv')

df.info()

df.head()

cols = df[['Case Number','Primary Type','Description','Location Description','Latitude','Longitude','Arrest']]

cols.isnull().sum()

cols.dtypes

"""# DataFrame Export"""

y = []
for i in range(len(cols)):
    x = tuple(cols.iloc[i])  # Use 'cols' instead of 'df' here
    y.append(x)

file = open('Us_crime_report.txt', 'w')

for t in y:
    file.write(str(t) + ',' + '\n')

file.close()
